### ISSUE TITLE
remontoire is empty

### ISSUE THREAD

**Issue by anthonymobile** [regolith-linux/remontoire#4]
the key binding help in the Remontoire popup (super-?) suddenly vanished. now it only displays an empty table with Action | Keybinding at the top.

not exactly sure when it happened, but i think it was soon after i staged my ~/.config/regolith/i3/config file
![Screenshot from 2020-03-07 23-17-13](https://user-images.githubusercontent.com/121955/76156533-d36c3b00-60c9-11ea-86e4-437cb664f165.png)

**Comment by anthonymobile** [comment]
yeah that was it. unstaged and its fine. user error? followed these https://regolith-linux.org/docs/howto/stage-configs/

**Comment by kgilmer** [comment]
Hi @anthonymobile , a few people have called this out, sorry for the confusion.  What happened is that the i3 config file changed between 1.3 and 1.3.1 such that the comment format was modified so that Remontoire could read it directly from the config.  Before the shortcuts were simply hardcoded in the program.  You copied the older version of the i3 config and so Remontoire isn't finding any keybindings.  I put a mention of the issue on the [release notes page](https://regolith-linux.org/docs/reference/releases/regolith-1.3.1-release-notes/).  To fix the issue, kindly re-copy the i3 config file from `/etc/regolith/i3/config` to `~/.config/regolith/i3/config` and add your changes back in.
