### ISSUE TITLE
i3rocks wifi widget makes remontoire appear and dissappear on its own

### ISSUE THREAD

**Issue by anthonymobile** [regolith-linux/remontoire#5]
sorry wasn't sure how to describe this issue (or if it goes here)

i staged an i3rocks config file which is working fine, but when i uncommitted the wifi widget block

```
# Wifi
#
# Displays the wifi network's name
# If the auto-discovered wifi device is incorrect,
# override the "instance" value with the desired device
#[wifi2]
# Replace with your wifi device if you need on next line
# instance=wlp2s0
# interval=5
```

on reboot it caused Remontoire to start appearing and dismissing itself every 5 seconds (+ the wifi block didnt work either). commenting this back out fixed it. not clear how these would interact?

**Comment by kgilmer** [comment]
I repro'd what I think your setup is:
1. stage i3 and i3xrocks files
2. uncomment wifi2 block in user staged i3xrocks file
3. restart i3

I do not see any issue with Remontoire.  Looking at the source for the blocks, only the "info" block references it, so perhaps there is a change there that you don't realize?  What happens if you remove the `info` block altogether from your i3xrocks config?

**Comment by kgilmer** [comment]
Any update @anthonymobile ?

**Comment by anthonymobile** [comment]
I think you are right, it must have been another config issue. Unfortunately I had an unrelated file system corruption and ended up rebuilding the system entirely so I can’t update this. I think u can close it.
  

  
  

  
  
>
