### ISSUE TITLE
[Fedora] Settings schema not installed

### ISSUE THREAD

**Issue by sigboe** [regolith-linux/remontoire#7]
In Fedora I get 

```
(process:966526): GLib-GIO-ERROR **: 19:22:00.843: Settings schema 'org.regolith-linux.remontoire' is not installed
```
when trying to run the program after compiling.

**Comment by kgilmer** [comment]
Hi @sigboe , oh I forgot that the gsettings schema needs to be installed on your system.  To do this run `sudo ninja install` from within the build directory and the gsettings schema should then be installed and you can run the program.

I will update the readme and then close this issue if you get it to work as well.

**Comment by sigboe** [comment]
That works! 
There are still some issues and some questions though.
When I try to run it I get this error
```
(remontoire:1532305): Gdk-CRITICAL **: 08:35:15.677: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
```
And the window launches on the wrong monitor, it always launches on the left monitor, except sometimes it launches on my primary monitor and then jumps to the left monitor.

And also the window did not inherit the gtk theme.

And my questions are, how would I go about making an rpm package?
And is there a way to open and close the categories without ~~getting arthritis~~ using the mouse? Preferably using hjkl as arrow keys.

**Comment by kgilmer** [comment]
> When I try to run it I get this error
```
(remontoire:1532305): Gdk-CRITICAL **: 08:35:15.677: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
```

Yes, I don't believe this is a serious error despite it's wording.  I haven't tracked this down yet.

> And the window launches on the wrong monitor, it always launches on the left monitor, except sometimes it launches on my primary monitor and then jumps to the left monitor.

Yes, we need a way of specifying which monitor the dialog should appear on.  This is a feature request.

> And also the window did not inherit the gtk theme.

Hmmm...can you send a screenshot?  I have not seen this issue before.

> And my questions are, how would I go about making an rpm package?

I wish I knew how to do this!  I believe there is plenty of tutorial info online but haven't really spent much time on RPM packaging.  If you do manage to get it packaged though please let me know! :smile: 

> And is there a way to open and close the categories without getting arthritis using the mouse? Preferably using hjkl as arrow keys.

This is also a feature request and a bit difficult.  Due to it's nature, the window should not be in focus, so to respond to keyboard sequences it needs to be able to listen globally for keyboard events.  I haven't looked into it but agree it's a useful addition.

Thanks for the feedback!

**Comment by sigboe** [comment]
> Hmmm...can you send a screenshot? I have not seen this issue before.

Sorry it appears that no gtk application have the theme which I can see in the UI is selected. It might have happened since I upgraded the major release of my distro. (which I will also do next time I reboot hehe). I fixed it by changing the gtk settings in `.config` instead.

Last question for this issue, would it be possible to do a portable build, which didn't require the schema to be installed? At least until its in typical package repos, this would allow me to put it in `.local/bin/` which is both in my path and in my dotfiles git repository. Would have it on all my computers without compiling. And also my colleague who just has his own fork of my dotfiles and fetches commits from my repo.

**Comment by kgilmer** [comment]
I am not aware of how to change it so that the dconf schema is not required...I guess you're saying that you do not want to store any state (screen position, closed/open state of categories, padding) and always get the defaults?  If you are aware of the changes needed to make this work I will take a look.

Typically w/ dotfiles you may have a script that runs some initial code to setup the system.  If this is the case you could just add the `meson build && cd build && sudo ninja install` to your script, no?
